env:
  - CC="gcc -std=c99"
language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install: "pip install -r requirements.txt"
script:
  # command to run tests
  - python -m unittest
  # command to run python code check
  - python linter.py
  # run doc tests
  - python -m doctest pypuf/bipoly.py